
# Test generated by the DESTROYERNATOR
value_0=285
print value_0
value_1=-(195)
value_2=-(value_1)
print (-(((618) + (-(value_1))) + (-(-((-((-(142)) + (-(value_0)))) + (-((-(-((value_1) + (input())))) + (867)))))))) + (-(835))
value_3=(value_1) + (value_0)
