
# Test generated by the DESTROYERNATOR
value_0=285
print (-(-(input()))) + (value_0)
print -(-(-(-((value_0) + (value_0)))))
value_1=input()
value_2=-((-(value_1)) + ((610) + ((666) + ((input()) + (input())))))
value_3=(947) + (-(843))
print input()
value_4=-(value_2)
print value_1
print (-(((-((value_2) + (-(((input()) + (274)) + (value_4))))) + (365)) + (value_3))) + (value_1)
print -(689)
value_5=-(value_4)
print ((474) + (value_3)) + ((676) + ((-((-(input())) + (-(989)))) + ((417) + (170))))
print (412) + (value_2)
print -(value_1)
print input()
print 375
print value_5
print -(input())
print value_4
print ((396) + (input())) + ((949) + (value_3))
value_6=(value_5) + (-(-((((-(value_0)) + (-(value_1))) + ((-((((567) + (754)) + (value_2)) + (value_5))) + (825))) + (value_3))))
print (-(54)) + (-(-((250) + (((285) + ((522) + (-(value_0)))) + ((497) + (-(-(88))))))))
print value_6
print -((653) + ((value_5) + ((-((((input()) + (-(value_4))) + ((-(-(640))) + (-(-(((-(-(value_0))) + (-((value_4) + (882)))) + (687)))))) + (-(-(value_2))))) + ((value_2) + (96)))))
value_7=((((value_2) + ((-((-(value_4)) + (-(value_2)))) + (674))) + (input())) + ((((input()) + (input())) + (-(((value_0) + (679)) + (-(-(value_3)))))) + ((-((value_2) + ((-(-(555))) + (((-(-((((input()) + ((808) + ((value_5) + (input())))) + (-(297))) + (-(403))))) + (input())) + (-((input()) + (-(-(-(-((-(869)) + (-(33))))))))))))) + (413)))) + (value_0)
value_8=195
print -(input())
print -(246)
print value_7
value_9=(653) + ((-(-(input()))) + ((value_5) + (value_1)))
value_10=(value_1) + ((((-(((((value_2) + (input())) + ((-(-(-(((value_4) + (value_3)) + ((69) + (-(-(-(((-(value_2)) + (value_1)) + (497)))))))))) + (-(636)))) + (-((-(-(-(191)))) + (-(601))))) + ((641) + (252)))) + ((value_8) + (-(-(-(455)))))) + ((value_6) + (-(-(value_4))))) + (((-(-(-(-(106))))) + (value_4)) + ((-(-(-((value_7) + (((-(743)) + (556)) + (-((-(-(-((-(value_3)) + (value_5))))) + (-((-(-(input()))) + ((991) + (-(-(-(input())))))))))))))) + ((input()) + (-(value_8))))))
print -(908)
print -(532)
print (-(value_1)) + ((-(262)) + (-(-(-(-((-((929) + (-((-(-(input()))) + (-((-((value_5) + (value_3))) + (-(10)))))))) + ((-(185)) + (-(-(value_6))))))))))
value_11=-((576) + (-((input()) + (-((-(input())) + (input()))))))
value_12=557
print -(input())
print input()
print (-(((-(199)) + (-(value_2))) + (-(-(-(15)))))) + ((((input()) + (input())) + (input())) + ((value_11) + (value_3)))
print -(-(-(value_9)))
print input()
print (-((value_11) + (-(input())))) + (value_6)
print -(-(816))
print value_4
print -(-(-((638) + ((-((value_12) + (-(((-(value_12)) + (((value_2) + ((172) + (input()))) + ((value_12) + (value_7)))) + (207))))) + ((value_8) + ((551) + (-(value_5))))))))
value_13=((942) + (264)) + (input())
value_14=-(input())
print (921) + (input())
value_15=101
print -(-(-(((912) + (-(-((791) + (71))))) + (-(input())))))
