import random, sys

constants = ['value_0']
output = """
# Test generated by the DESTROYERNATOR
value_0=285
"""

range_upper_bound = 1001

fname = sys.argv[1]

def newConstant():
    name = "value_" + str(len(constants))
#    value = random.randrange(0, range_upper_bound)
#    output += name + "=" + str(value) + "\n"
    value = name + "=" + newTerm()
    constants.append(name)
    return value

def newTerm():
    val = random.randrange(0, 13)
    if val in range(0, 4):
        return "-(" + newTerm() + ")"
    elif val in range(4, 8):
        return "(" + newTerm() + ") + (" + newTerm() + ")"
    elif val in range(8, 10):
        return constants[random.randrange(0, len(constants))]
    elif val in range(10, 12):
        return str(random.randrange(0, range_upper_bound))
    elif val in range(12, 13):
        return "input()"

def doPrint():
    return "print " + newTerm()

for i in range(50):
    mode = random.randrange(0, 2)
    if mode == 0:
        output += newConstant() + "\n"
    elif mode == 1:
        output += "print " + newTerm() + "\n"

with open(fname+".py", 'w') as out_py:
    out_py.write(output)

with open(fname+".in", 'w') as out_test:
    num = output.count("input()")
    data = "\n".join([str(random.randrange(0, range_upper_bound)) for _ in range(0, num)])
    out_test.write(data)
